### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Craig-Macomber** [rambip/dioxus-markdown#1]
This project, as well as https://github.com/rambip/rust-web-markdown don't specify a license, which makes them implicitly fall under the full restrictions of copyright.

This disallows dioxus-markdown from being used in my own open source projects, as well as prevents me from making derived works, such as a version updated to to work with Dioxus 6.1.

If that is what you intended, that fine and I'll look for a different library to use, but if you would be ok putting this under an open source license, like the MIT license (which would be my preference), that would be wonderful since I'd love to use this library in my own project.

GitHub provides some documentation bout adding licenses here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks for creating this library, and I hope to use it soon :)

**Comment by rambip** [comment]
You're right, I didn't expect the project to have such success. This is done now.
